channel_sources:
  - conda-forge/label/rust_dev,conda-forge
polars_runtime:
  - "32"
  - "64"
  - "compat"
github_actions_labels:               # [win]
  - namespace-profile-8cpu-on-win-64 # [win]
rust_compiler_version:
  - 1.96.0
