{% set name = "polars" %}
{% set version = "0.13.52" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polars-{{ version }}.tar.gz
    sha256: 0974f868133b9dfdd88c29b36f5469da37dc9c4f2243977ba58f8ae4b22635c8

build:
  number: 0
  skip: true  # [py<37]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - posix                               # [win]
    - cmake
    - make                                # [unix]
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin >=0.12.11,<0.13
  run:
    - python
    - numpy >=1.16.0
    - typing_extensions >=4.0.0            # [py<310]

test:
  imports:
    - polars
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pola-rs/polars
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Polars is a blazingly fast DataFrames library implemented in Rust using Apache Arrow(2) as memory model.
  doc_url: https://pola-rs.github.io/polars-book/user-guide/index.html
  dev_url: https://github.com/pola-rs/polars

extra:
  recipe-maintainers:
    - Maxyme
    - timkpaine
    - ritchie46
    - sugatoray
    - xhochy
    - dhirschfeld
