{% set version = "1.19.0" %}

# Note: This recipe is specifically designed to work well with the autotick bot.
# Also refer to https://github.com/conda-forge/rust-feedstock/blob/main/recipe/meta.yaml.
package:
  name: {{ polars_variant }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/p/polars/polars-{{ version }}.tar.gz  # [polars_variant == "polars"]
    sha256: b52ada5c43fcdadf64f282522198c5549ee4e46ea57d236a4d7e572643070d9d  # [polars_variant == "polars"]
  - url: https://pypi.org/packages/source/p/polars-lts-cpu/polars_lts_cpu-{{ version }}.tar.gz  # [polars_variant == "polars-lts-cpu"]
    sha256: 6b404b092173ab5d21cdab1e3406240c34ccace6f1954a780436333f4fe5d5bb  # [polars_variant == "polars-lts-cpu"]
  - url: https://pypi.org/packages/source/p/polars-u64-idx/polars_u64_idx-{{ version }}.tar.gz  # [polars_variant == "polars-u64-idx"]
    sha256: dc2927cb7a0dfd638f173671d96c8b4ae6ff9bc6a257a1651781e979ea6f0600  # [polars_variant == "polars-u64-idx"]
    patches:
      - 0001-Patch-libz-ng-sys.patch  # [target_platform == "win-64"]


build:
  number: 0

requirements:
  build:
    - python                              # [build_platform != target_platform]
    # there is no cross-python for linux-64 -> win-64
    - cross-python_{{ target_platform }}  # [build_platform != target_platform and not target_platform == "win-64"]
    - crossenv                            # [build_platform != target_platform]
    - maturin >=1.3.2,<2                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}               # [win]
    # clang_win-64 already adds all required run_exports for the windows build
    - {{ stdlib("c") }}  # [not (build_platform != target_platform and target_platform == "win-64")]
    - {{ compiler('rust') }}
    - posix                               # [build_platform == "win-64"]
    - cmake
    - make                                # [unix]
    - cargo-feature                       # [build_platform != target_platform and target_platform == "win-64"]
    - cargo-patch                         # [build_platform != target_platform and target_platform == "win-64"]
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - maturin >=1.3.2,<2
  run:
    - python
    - numpy >=1.16.0
    - backports.zoneinfo                   # [py<39]
    - typing_extensions >=4.0.0            # [py<311]
    - packaging                            # [py>=310]

test:
  imports:
    - polars
  commands:
    - pip check
    - python -c "from polars import DataFrame"
  requires:
    - pip

about:
  home: https://github.com/pola-rs/polars
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Polars is a blazingly fast DataFrames library implemented in Rust using Apache Arrow(2) as memory model.
  doc_url: https://pola-rs.github.io/polars-book/user-guide/index.html
  dev_url: https://github.com/pola-rs/polars

extra:
  recipe-maintainers:
    - borchero
    - Maxyme
    - timkpaine
    - ritchie46
    - sugatoray
    - xhochy
    - dhirschfeld
    - pavelzw
    - '0xbe7a'
