context:
  version: "1.34.0.deprecated"
  build_number: 0

recipe:
  name: polars
  version: ${{ version }}

build:
  number: ${{ build_number }}

outputs:
  - package:
      name: polars-lts-cpu
    build:
      noarch: generic
    requirements:
      run:
        - polars >=1.34.0
        - polars-runtime-compat >=1.34.0
    tests:
      - python:
          pip_check: true
          imports:
            - polars

  - package:
      name: polars-u64-idx
    build:
      noarch: generic
    requirements:
      run:
        - polars >=1.34.0
        - polars-runtime-64 >=1.34.0
    tests:
      - python:
          pip_check: true
          imports:
            - polars

about:
  homepage: https://github.com/pola-rs/polars
  license: MIT
  license_file: []
  summary: Dataframes powered by a multithreaded, vectorized query engine, written in Rust
  description: Polars is a DataFrame interface on top of an OLAP Query Engine implemented in Rust using Apache Arrow Columnar Format as the memory model.
  documentation: https://docs.pola.rs
  repository: https://github.com/pola-rs/polars

extra:
  recipe-maintainers:
    - borchero
    - Maxyme
    - timkpaine
    - ritchie46
    - sugatoray
    - xhochy
    - dhirschfeld
    - pavelzw
    - "0xbe7a"
