azure:
  free_disk_space: true
  max_parallel: 25
  settings_linux:
    swapfile_size: 15GiB
  settings_win:
    variables:
      CONDA_BLD_PATH: C:\\bld\\
      SET_PAGEFILE: 'True'
bot:
  automerge: true
build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_64
conda_build:
  pkg_format: '2'
conda_build_tool: rattler-build
conda_forge_output_validation: true
conda_install_tool: pixi
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  linux_ppc64le: default
test: native_and_emulated
