bot:
  automerge: true
build_platform:
  linux_aarch64: linux_aarch64
  osx_arm64: osx_64
provider:
  linux_aarch64: travis
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
travis:
  linux_aarch64:
    type: arm64-graviton2
    size: large
conda_build:
  pkg_format: '2'
idle_timeout_minutes: 60
