# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: toml -*-

#                             VVVVVV  minimum `pixi` version
"$schema" = "https://pixi.sh/v0.36.0/schema/manifest/schema.json"

[project]
name = "polars-feedstock"
version = "3.48.1"  # conda-smithy version used to generate this file
description = "Pixi configuration for conda-forge/polars-feedstock"
authors = ["@conda-forge/polars"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]

[dependencies]
conda-build = ">=24.1"
conda-forge-ci-setup = "4.*"
rattler-build = "*"

[tasks]
[tasks.inspect-all]
cmd = "inspect_artifacts --all-packages"
description = "List contents of all packages found in rattler-build build directory."
[tasks.build]
cmd = "rattler-build build --recipe recipe"
description = "Build polars-feedstock directly (without setup scripts), no particular variant specified"
[tasks."build-linux_64_polars_variantdefault"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_polars_variantdefault.yaml"
description = "Build polars-feedstock with variant linux_64_polars_variantdefault directly (without setup scripts)"
[tasks."inspect-linux_64_polars_variantdefault"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_polars_variantdefault.yaml"
description = "List contents of polars-feedstock packages built for variant linux_64_polars_variantdefault"
[tasks."build-linux_64_polars_variantlts-cpu"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_polars_variantlts-cpu.yaml"
description = "Build polars-feedstock with variant linux_64_polars_variantlts-cpu directly (without setup scripts)"
[tasks."inspect-linux_64_polars_variantlts-cpu"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_polars_variantlts-cpu.yaml"
description = "List contents of polars-feedstock packages built for variant linux_64_polars_variantlts-cpu"
[tasks."build-linux_64_polars_variantu64-idx"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_polars_variantu64-idx.yaml"
description = "Build polars-feedstock with variant linux_64_polars_variantu64-idx directly (without setup scripts)"
[tasks."inspect-linux_64_polars_variantu64-idx"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_polars_variantu64-idx.yaml"
description = "List contents of polars-feedstock packages built for variant linux_64_polars_variantu64-idx"
[tasks."build-linux_aarch64_polars_variantdefault"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_aarch64_polars_variantdefault.yaml"
description = "Build polars-feedstock with variant linux_aarch64_polars_variantdefault directly (without setup scripts)"
[tasks."inspect-linux_aarch64_polars_variantdefault"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_aarch64_polars_variantdefault.yaml"
description = "List contents of polars-feedstock packages built for variant linux_aarch64_polars_variantdefault"
[tasks."build-linux_aarch64_polars_variantlts-cpu"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_aarch64_polars_variantlts-cpu.yaml"
description = "Build polars-feedstock with variant linux_aarch64_polars_variantlts-cpu directly (without setup scripts)"
[tasks."inspect-linux_aarch64_polars_variantlts-cpu"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_aarch64_polars_variantlts-cpu.yaml"
description = "List contents of polars-feedstock packages built for variant linux_aarch64_polars_variantlts-cpu"
[tasks."build-linux_aarch64_polars_variantu64-idx"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_aarch64_polars_variantu64-idx.yaml"
description = "Build polars-feedstock with variant linux_aarch64_polars_variantu64-idx directly (without setup scripts)"
[tasks."inspect-linux_aarch64_polars_variantu64-idx"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_aarch64_polars_variantu64-idx.yaml"
description = "List contents of polars-feedstock packages built for variant linux_aarch64_polars_variantu64-idx"
[tasks."build-linux_ppc64le_"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_ppc64le_.yaml"
description = "Build polars-feedstock with variant linux_ppc64le_ directly (without setup scripts)"
[tasks."inspect-linux_ppc64le_"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_ppc64le_.yaml"
description = "List contents of polars-feedstock packages built for variant linux_ppc64le_"
[tasks."build-osx_64_polars_variantdefault"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_64_polars_variantdefault.yaml"
description = "Build polars-feedstock with variant osx_64_polars_variantdefault directly (without setup scripts)"
[tasks."inspect-osx_64_polars_variantdefault"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_polars_variantdefault.yaml"
description = "List contents of polars-feedstock packages built for variant osx_64_polars_variantdefault"
[tasks."build-osx_64_polars_variantlts-cpu"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_64_polars_variantlts-cpu.yaml"
description = "Build polars-feedstock with variant osx_64_polars_variantlts-cpu directly (without setup scripts)"
[tasks."inspect-osx_64_polars_variantlts-cpu"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_polars_variantlts-cpu.yaml"
description = "List contents of polars-feedstock packages built for variant osx_64_polars_variantlts-cpu"
[tasks."build-osx_64_polars_variantu64-idx"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_64_polars_variantu64-idx.yaml"
description = "Build polars-feedstock with variant osx_64_polars_variantu64-idx directly (without setup scripts)"
[tasks."inspect-osx_64_polars_variantu64-idx"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_polars_variantu64-idx.yaml"
description = "List contents of polars-feedstock packages built for variant osx_64_polars_variantu64-idx"
[tasks."build-osx_arm64_polars_variantdefault"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_polars_variantdefault.yaml"
description = "Build polars-feedstock with variant osx_arm64_polars_variantdefault directly (without setup scripts)"
[tasks."inspect-osx_arm64_polars_variantdefault"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_polars_variantdefault.yaml"
description = "List contents of polars-feedstock packages built for variant osx_arm64_polars_variantdefault"
[tasks."build-osx_arm64_polars_variantlts-cpu"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_polars_variantlts-cpu.yaml"
description = "Build polars-feedstock with variant osx_arm64_polars_variantlts-cpu directly (without setup scripts)"
[tasks."inspect-osx_arm64_polars_variantlts-cpu"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_polars_variantlts-cpu.yaml"
description = "List contents of polars-feedstock packages built for variant osx_arm64_polars_variantlts-cpu"
[tasks."build-osx_arm64_polars_variantu64-idx"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_polars_variantu64-idx.yaml"
description = "Build polars-feedstock with variant osx_arm64_polars_variantu64-idx directly (without setup scripts)"
[tasks."inspect-osx_arm64_polars_variantu64-idx"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_polars_variantu64-idx.yaml"
description = "List contents of polars-feedstock packages built for variant osx_arm64_polars_variantu64-idx"
[tasks."build-win_64_polars_variantdefault"]
cmd = "rattler-build build --recipe recipe -m .ci_support/win_64_polars_variantdefault.yaml"
description = "Build polars-feedstock with variant win_64_polars_variantdefault directly (without setup scripts)"
[tasks."inspect-win_64_polars_variantdefault"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/win_64_polars_variantdefault.yaml"
description = "List contents of polars-feedstock packages built for variant win_64_polars_variantdefault"
[tasks."build-win_64_polars_variantlts-cpu"]
cmd = "rattler-build build --recipe recipe -m .ci_support/win_64_polars_variantlts-cpu.yaml"
description = "Build polars-feedstock with variant win_64_polars_variantlts-cpu directly (without setup scripts)"
[tasks."inspect-win_64_polars_variantlts-cpu"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/win_64_polars_variantlts-cpu.yaml"
description = "List contents of polars-feedstock packages built for variant win_64_polars_variantlts-cpu"
[tasks."build-win_64_polars_variantu64-idx"]
cmd = "rattler-build build --recipe recipe -m .ci_support/win_64_polars_variantu64-idx.yaml"
description = "Build polars-feedstock with variant win_64_polars_variantu64-idx directly (without setup scripts)"
[tasks."inspect-win_64_polars_variantu64-idx"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/win_64_polars_variantu64-idx.yaml"
description = "List contents of polars-feedstock packages built for variant win_64_polars_variantu64-idx"

[feature.smithy.dependencies]
conda-smithy = "*"
[feature.smithy.tasks.build-locally]
cmd = "python ./build-locally.py"
description = "Build packages locally using the same setup scripts used in conda-forge's CI"
[feature.smithy.tasks.smithy]
cmd = "conda-smithy"
description = "Run conda-smithy. Pass necessary arguments."
[feature.smithy.tasks.rerender]
cmd = "conda-smithy rerender"
description = "Rerender the feedstock."
[feature.smithy.tasks.lint]
cmd = "conda-smithy lint --conda-forge recipe"
description = "Lint the feedstock recipe"

[environments]
smithy = ["smithy"]
# This is a copy of default, to be enabled by build_steps.sh during Docker builds
# __PLATFORM_SPECIFIC_ENV__ = []
